services:
  - type: web
    name: poohter-wholeseller-website
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EXPO_PUBLIC_API_URL
        value: https://api.poohter.com
